{
  "items": [
    ["White Scroll", "false", "garbage", 0, 0, "A white scroll, nothing special.", "none", ""],
    ["Light Armor", "false", "armor", 0, 1, "A light set of armor.", "none", ""],
    ["White Blob", "false", "garbage", 0, 0, "It's a white blob of unknown material.. seems harmless.", "none", ""],
    ["Wine", "false", "consumable", 1, 1, "It's a bottle of wine.", "stamina", "You drink the Wine and feel slightly drunk."],
    ["Light Sword", "false", "weapon", 0, 1, "It's a light sword, point away from self.", "none", ""],
    ["Pouch", "false", "consumable", 1, 1, "A silk white pouch - I wonder what's inside!", "stamina", "I hope you're ready.. for nothing!"],
    ["Line", "false", "nothing", 0, 0, "You see a line.", "none", ""],
    ["Smily Face", "false", "garbage", 0, 0, "It's a smily face, it seems.. happy.", "none", ""],
    ["Desk", "true", "nothing", 0, 0, "You see a wooden desk.", "none", ""],
    ["Smelly Fish", "false", "weapon", 0, 1, "It's a large, smelly fish.", "none", ""],
    ["Gold Chalice", "false", "container", 25, 100, "It's a golden chalice - looks valuable!", "none", ""],
    ["Heavy Sword", "false", "weapon", 1, 2, "It's a heavy sword, this looks like it could do some damage.", "none", ""],
    ["Shrub", "true", "nothing", 0, 0, "It's a small green shrub.", "none", ""],
    ["Tree", "true", "nothing", 0, 0, "It's a large ashe tree.", "none", ""],
    ["Chest", "true", "container", 0, 0, "It's a solid chest, definitely not a mimic..", "none", ""],
    ["Pop", "false", "nothing", 0, 0, "* POP *", "none", ""],
    ["Magic Pillar", "true", "nothing", 0, 0, "It's a strange, magical device.", "none", ""],
    ["Orb Stand", "true", "nothing", 0, 0, "It's a shiny blue orb on a metal stand.", "none", ""],
    ["Dog Bone", "false", "useable", 0, 0, "It's a magical dog treat!", "none", ""],
    ["Small Fish", "false", "garbage", 0, 0, "It's a small fish.", "none", ""],
    ["Sign", "true", "sign", 0, 0, "<Insert dynamic sign message here>", "none", ""],
    ["Pillar", "true", "nothing", 0, 0, "It's a tall stone pillar.", "none", ""],
    ["Razorhawk Statue", "true", "nothing", 0, 0, "A gleaming golden statue of Razorhawk (who's that?).", "none", ""],
    ["Mirror", "true", "nothing", 0, 0, "A large mirror.", "none", ""],
    ["Pile of Gold", "false", "container", 100, 100, "A pile of gold coins!", "none", ""],
    ["Mechs Laptop", "true", "nothing", 0, 0, "You see a laptop on top of a desk belonging to Mech.", "none", ""],
    ["Motorheds Cat", "false", "garbage", 0, 0, "You see a cat belonging to Motorhed.", "none", ""],
    ["Mahogany Desk", "true", "nothing", 0, 0, "You see a sturdy mahogany desk.", "none", ""],
    ["Chair Right", "false", "nothing", 0, 0, "You see a wooden chair.", "none", ""],
    ["Chair Down", "false", "nothing", 0, 0, "You see a wooden chair.", "none", ""],
    ["Chest Open", "true", "container", 0, 0, "It's a solid chest, definitely not a mimic..", "none", ""],
    ["Green Tonic", "false", "buff", 1, 1, "An invigorating green bottle of tonic.", "stamina", ""],
    ["Painting Right", "false", "nothing", 0, 0, "You see a beautiful painting by C.H. Wolf.", "none", ""],
    ["Painting Down", "false", "nothing", 0, 0, "You see a beautiful painting by C.H. Wolf.", "none", ""],
    ["Gravestone Right", "true", "nothing", 0, 0, "You see an old gravestone, but can't make out the markings.", "none", ""],
    ["Gravestone Down", "true", "nothing", 0, 0, "You see an old gravestone, but can't make out the markings.", "none", ""],
    ["Window Right", "false", "nothing", 0, 0, "You see a window, but it's too dirty to see through.", "none", ""],
    ["Window Down", "false", "nothing", 0, 0, "You see a window, but it's too dirty to see through.", "none", ""],
    ["Big Mech", "false", "consumable", 1, 1, "It's a Big Mech sandwich!", "hp", "You eat the Big Mech sandwich.. you don't feel great."],
    ["Hamburger", "false", "consumable", 1, 1, "It's a hamburger - weird.", "hp", "You eat the Hamburger, it was pretty good."],
    ["Flower", "false", "consumable", 1, 1, "It's a pretty white flower, possibly a daisy.", "stamina", "You ate the flower.. why?"],
    ["Stairs", "true", "portal", 0, 0, "You see a large staircase.", "none", ""],
    ["Bones", "false", "nothing", 0, 0, "A pile of bones.. gross.", "none", ""],
    ["Blood Chalice", "false", "consumable", -100, -100, "A chalice full of blood.. I don't want to drink this..", "hp", "You force down the contents of the Blood Chalice.. and die."],
    ["Hot Sauce", "false", "garbage", 0, 0, "A bottle of hot sauce.", "none", ""],
    ["Red Skull", "false", "nothing", 0, 0, "A red skull.. what could this have belonged to?!", "none", ""],
    ["Herb", "false", "consumable", 100, 100, "An herb, this will make you feel good.", "stamina", "You use the Herb and feel great!"],
    ["Blue Crab", "false", "garbage", 0, 0, "A blue crab, I wonder who would want this?", "none", ""],
    ["Leaf", "false", "consumable", 25, 25, "This leaf looks tasty.", "stamina", "You use the leaf and feel refreshed."],
    ["Perfume", "false", "garbage", 0, 0, "A bottle of perfume.", "none", ""],
    ["Blueberry Jam", "false", "consumable", 1, 1, "A bottle of blueberry jam.", "hp", "You eat the Bluebery Jam, it's berrylicious."],
    ["Ketchup", "false", "garbage", 0, 0, "A bottle of ketchup.", "none", ""],
    ["Vinegar", "false", "garbage", 0, 0, "A bottle of vinegar.", "none", ""],
    ["Jolt Cola", "false", "consumable", 100, 100, "A refreshing bottle of Jolt Cola!", "stamina", "You drink the Jolt Cola and feel energized!"],
    ["Coffee", "false", "consumable", 10, 10, "A cup 'o joe.", "stamina", "You drink the coffee and feel refreshed."],
    ["Bloody Knives", "false", "nothing", 0, 0, "You see some bloody knives, a butchers.. hopefully?", "none", ""],
    ["Green Scroll", "false", "useable", 0, 0, "A magical green scroll!", "none", ""],
    ["Dark Blue Scroll", "false", "useable", 0, 0, "A magical dark blue scroll!", "none", ""],
    ["Yellow Scroll", "false", "useable", 0, 0, "A magical yellow scroll!", "none", ""],
    ["Fountain", "true", "interactable", 100, 100, "A magical fountain flowing with energy!", "none", ""],
    ["Statue", "true", "nothing", 0, 0, "A golden statue.", "none", ""],
    ["Gem", "false", "garbage", 0, 0, "A pristine gem, this looks valuable.", "none", ""],
    ["NPC Alchemist", "true", "npc", 0, 0, "You see the Alchemist standing there in flowing purple robes.", "none", ""],
    ["NPC 1", "true", "npc", 0, 0, "NPC 1", "none", ""],
    ["NPC 2", "true", "npc", 0, 0, "NPC 2", "none", ""],
    ["Andy", "true", "npc", 0, 0, "You see Andy. Andy likes crabs.", "none", ""],
    ["NPC 3", "true", "npc", 0, 0, "NPC 3", "none", ""],
    ["Ted the Armorer", "true", "npc", 0, 0, "You see Ted the Armorer!", "none", ""],
    ["NPC 4", "true", "npc", 0, 0, "NPC 4", "none", ""],
    ["Unlit Torch Right", "false", "interactable", 0, 0, "You see an unlit torch.", "none", ""],
    ["Lit Torch Right", "false", "interactable", 0, 0, "You see a lit torch.", "none", ""],
    ["Unlit Torch Down", "false", "interactable", 0, 0, "You see an unlit torch.", "none", ""],
    ["Lit Torch Down", "false", "interactable", 0, 0, "You see a lit torch.", "none", ""],
    ["Bar Table", "true", "nothing", 0, 0, "You see a messy bar table full of food and drink.", "none", ""],
    ["Scarecrow", "true", "nothing", 0, 0, "You see a scarecrow.", "none", ""],
    ["Rock", "false", "nothing", 0, 0, "You see a rock.", "none", ""],
    ["Crushed Rock", "false", "nothing", 0, 0, "You see a crushed rock.", "none", ""],
    ["Pebbles", "false", "nothing", 0, 0, "You see pebbles scattered on the floor.", "none", ""],
    ["Stalagmite Spikes", "true", "nothing", 0, 0, "You see stalagmite spikes sticking up from the ground.", "none", ""],
    ["Evergreen Tree", "true", "nothing", 0, 0, "You seen an evergreen tree. It is green.", "none", ""],
    ["Swamp Sign", "true", "sign", 0, 0, "<Insert dynamic sign message here>", "none", ""],
    ["Dust Bunny", "false", "nothing", 0, 0, "It's a dust bunny, ew.", "none", ""],
    ["Frog", "false", "nothing", 0, 0, "Ribbit.", "none", ""],
    ["Squirrel", "false", "nothing", 0, 0, "A little squirrel, cute.", "none", ""],
    ["Lizard", "false", "nothing", 0, 0, "LIZARD!", "none", ""],
    ["Fish Bones", "false", "weapon", 0, 6, "Fish sword!! Ultimate power!", "none", ""],
    ["Stalagmite", "true", "nothing", 0, 0, "A stalagmite.", "none", ""],
    ["Golden Slayer", "false", "weapon", 1, 4, "The golden slayer, a sword that lives up to it's name.", "none", ""],
    ["Demon Slayer", "false", "weapon", 2, 4, "A vicious looking sword..", "none", ""],
    ["Fake Lightsaber", "false", "weapon", 1, 3, "A (fake) lightsaber - oh boy!", "none", ""],
    ["Club", "false", "weapon", 0, 3, "A large wooden club.", "none", ""],
    ["Silver Coins", "false", "garbage", 0, 0, "A pile of silver coins.", "none", ""],
    ["Head on a Pike", "true", "nothing", 0, 0, "It's a head on a pike, yikes..", "none", ""],
    ["Painting 2 Right", "false", "nothing", 0, 0, "A beautiful painting by C.H. Wolf.", "none", ""],
    ["Painting 2 Down", "false", "nothing", 0, 0, "A beautiful painting by C.H. Wolf.", "none", ""],
    ["Beer", "false", "consumable", 1, 1, "A 6-pack of brews.", "stamina", "You drink the beer and feel buzzed."],
    ["Red Scroll", "false", "useable", 0, 0, "A magical red scroll!", "none", ""],
    ["Purple Scroll", "false", "useable", 0, 0, "A magical purple scroll!", "none", ""],
    ["Light Blue Scroll", "false", "useable", 0, 0, "A magical light blue scroll!", "none", ""],
    ["Pink Scroll", "false", "useable", 0, 0, "A magical pink scroll!", "none", ""],
    ["Grey Scroll", "false", "useable", 0, 0, "A magical grey scroll!", "none", ""],
    ["Silver Scroll", "false", "useable", 0, 0, "A magical silver scroll!", "none", ""],
    ["Brown Scroll", "false", "useable", 0, 0, "A magical brown scroll!", "none", ""],
    ["Water Robe", "false", "armor", 3, 4, "A magical water robe!", "none", ""],
    ["Fruit Garb", "false", "armor", 2, 3, "A fruit garb.", "none", ""],
    ["Tentacle", "false", "nothing", 0, 0, "A green slimy tentacle - eek!", "none", ""],
    ["Gold Coin", "false", "container", 1, 1, "A gold coin!", "none", ""],
    ["2 Gold Coins", "false", "container", 3, 3, "Gold coins!", "none", ""],
    ["3 Gold Coins", "false", "container", 3, 3, "Gold coins!", "none", ""],
    ["4 Gold Coins", "false", "container", 4, 4, "Gold coins!", "none", ""],
    ["Small Pile of Gold Coins", "false", "container", 5, 10, "A small pile of gold coins!", "none", ""],
    ["Coral", "true", "nothing", 0, 0, "Some spiky green coral.", "none", ""],
    ["Nut", "false", "garbage", 0, 0, "It's a nut.", "none", ""],
    ["Warhammer", "false", "weapon", 0, 4, "A mighty warhammer!", "none", ""],
    ["Cactus", "true", "nothing", 0, 0, "A spiky cactus, don't get pricked!", "none", ""],
    ["Small Cactus", "true", "nothing", 0, 0, "A spiky cactus, don't get pricked!", "none", ""],
    ["Shadow Monster", "false", "nothing", 0, 0, "A shadow monster - spooky!", "none", ""],
    ["Plant Growth", "false", "nothing", 0, 0, "It's a growth.. you should get that checked out.", "none", ""],
    ["Book", "false", "garbage", 0, 0, "It's a blank book, perfect for writing in.", "none", ""],
    ["Worm", "false", "garbage", 0, 0, "Ew, it's a worm.", "none", ""],
    ["Yellow Potion", "true", "interactable", 0, 0, "A mysterious yellow potion.", "none", ""],
    ["NPC 5", "true", "npc", 0, 0, "NPC 5", "none", ""],
    ["NPC 6", "true", "npc", 0, 0, "NPC 6", "none", ""],
    ["Krink", "false", "nothing", 0, 0, "* KRINK! *", "none", ""],
    ["NPC Faerie", "true", "npc", 0, 0, "You see a faerie, woah!", "none", ""],
    ["Royal Armor", "false", "armor", 4, 6, "A royal set of armor!", "none", ""],
    ["Dragon Pillar", "true", "nothing", 0, 0, "A huge dragon pillar!", "none", ""],
    ["Turtle", "false", "nothing", 0, 0, "It's a turtle. He appears to be hiding in his shell.", "none", ""],
    ["Swamp Eye", "true", "nothing", 0, 0, "As you stand examining this creature, you suddenly feel you should back away.", "none", ""],
    ["Gloves", "false", "armor", 3, 4, "A sturdy pair of gloves.", "none", ""],
    ["Life Rune", "false", "useable", 25, 25, "This is the life rune! The combined power of all the runes!", "hp", ""],
    ["Spirit Rune", "false", "buff", 2, 2, "This is a spirit rune!", "stamina", ""],
    ["Mind Rune", "false", "buff", 1, 1, "This is a mind rune!", "magic", ""],
    ["Body Rune", "false", "buff", 2, 2, "This is a body rune!", "hp", ""],
    ["Belt", "false", "armor", 0, 3, "A shiny golden belt.", "none", ""],
    ["Vase", "false", "nothing", 0, 0, "A delicate vase.", "none", ""],
    ["Pillow", "false", "garbage", 0, 0, "A delicate cotton pillow.", "none", ""],
    ["Lint", "false", "garbage", 0, 0, "Ew, lint.", "none", ""],
    ["Birds Nest", "false", "interactable", 0, 0, "A birds nest - I wonder what's inside?", "none", ""],
    ["Crystal Ball", "false", "consumable", 10, 10, "A magical crystal ball.. don't smash it.", "magic", "You smash the crystal ball and feel the magic inside refresh you."],
    ["Unlit Fire Pedestal", "true", "interactable", 0, 0, "An unlit fire pedestal.", "none", ""],
    ["Lit Fire Pedestal", "true", "interactable", 0, 0, "A lit fire pedestal.", "none", ""],
    ["Balloon", "false", "interactable", 0, 0, "A balloon!", "none", ""],
    ["Flatty", "false", "nothing", 0, 0, "It's a flatty!", "none", ""],
    ["Green Flagpole", "true", "nothing", 0, 0, "It's a flagpole with a green flag blowing in the wind.", "none", ""],
    ["Yellow Flagpole", "true", "nothing", 0, 0, "It's a flagpole with a yellow flag blowing in the wind.", "none", ""],
    ["Flag Pole 1", "true", "nothing", 0, 0, "It's a flag pole.", "none", ""],
    ["Flag Pole 2", "true", "nothing", 0, 0, "It's a flag pole.", "none", ""],
    ["Green Flag", "false", "garbage", 0, 0, "It's a green flag.", "none", ""],
    ["Yellow Flag", "false", "garbage", 0, 0, "It's a yellow flag.", "none", ""],
    ["Portal", "false", "portal", 0, 0, "It's a shimmering magic portal! I wonder where it leads..", "none", ""],
    ["Cement Wall", "true", "nothing", 0, 0, "A large cement wall.", "none", ""],
    ["Water Bowl", "false", "garbage", 0, 0, "It's a bowl of water. This could be useful for someone lost in the desert..", "none", ""],
    ["Poo", "false", "nothing", 0, 0, "Someone took a poo on the floor.....", "none", ""],
    ["Seashell Armor", "false", "armor", 4, 5, "Powerful sea shell armor.", "none", ""],
    ["Earth Armor", "false", "armor", 2, 4, "Earth Armor.", "none", ""],
    ["Wooden Armor", "false", "armor", 3, 4, "A sturdy set of armor made of wood.", "none", ""],
    ["Royal Sword", "false", "weapon", 4, 6, "A royal sword!", "none", ""],
    ["Battleaxe", "false", "weapon", 3, 5, "A massive battleaxe, good for cutting wood - and people!", "none", ""],
    ["Steel Mace", "false", "weapon", 1, 2, "A steel mace.", "none", ""],
    ["Spiked Mace", "false", "weapon", 1, 3, "A spiky mace for poking holes in your enemies.", "none", ""],
    ["Stick", "false", "nothing", 0, 0, "It's a wooden stick, neat!", "none", ""],
    ["Shovel", "false", "weapon", 0, 2, "A metal shovel.", "none", ""],
    ["Red Potion", "true", "interactable", 0, 0, "A mysterious red potion.", "none", ""],
    ["Blue Potion", "true", "interactable", 0, 0, "A mysterious blue potion.", "none", ""],
    ["NPC 7","true","npc",0,0,"NPC 7", "none", ""],
  ["Gem","false","garbage",0,0,"A gem, this looks valuable!", "none", ""],
  ["Colored Gem","false","garbage",0,0,"A colorful gem, pretty!", "none", ""],
  ["Gem Shard","false","garbage",0,0,"A large gem shard.", "none", ""],
  ["Crushed Gem","false","garbage",0,0,"A crushed gem.", "none", ""],
  ["NPC 8","true","npc",0,0,"NPC 8", "none", ""],
  ["Stick Right","false","nothing",0,0,"It's a stick.", "none", ""],
  ["Stick Down","false","nothing",0,0,"It's a stick.", "none", ""],
  ["Flying Rock","false","nothing",0,0,"It's a flying rock, look out!", "none", ""],
  ["Drunken Dodgeball","false","garbage",0,0,"It's a dodgeball (it looks drunk).", "none", ""],
  ["Cool Dodgeball","false","garbage",0,0,"It's a dodgeball (too cool for school).", "none", ""],
  ["Angry Dodgeball","false","garbage",0,0,"It's a dodgeball (it looks angry).", "none", ""],
  ["Demon Pod","false","nothing",0,0,"You don't want to think about what's in that pod..", "none", ""],
  ["Treasure Chest","false","container",0,0,"It's a treasure chest, definitely not a mimic..", "none", ""],
  ["Unicorn","true","nothing",0,0,"WOAH! It's a unicorn!!", "none", ""],
  ["BRB","false","nothing",0,0,"They'll BRB.", "none", ""],
  ["Knight Down","true","interactable",0,0,"It's knights armor! (Is something moving inside?)", "none", ""],
  ["Knight Right","true","interactable",0,0,"It's knights armor! (Is something moving inside?)", "none", ""],
  ["NPC 9","true","npc",0,0,"NPC 9", "none", ""],
  ["Signpost","true","sign",0,0,"<INSERT DYNAMIC SIGN TEXT HERE>", "none", ""],
  ["Broken Dragon Pillar","true","nothing",0,0,"It's a broken dragon pillar. What could do this?!", "none", ""],
  ["Scorpion Tail","false","weapon",1,3,"It's a vicious scorpion tail!", "none", ""],
  ["Gate Down","true","interactable",0,0,"It's a locked metal gate, too bad you don't have a key.", "none", ""],
  ["NPC 10","true","npc",0,0,"NPC 10", "none", ""],
  ["Blue Water Creature Right","true","nothing",0,0,"You see a water creature peer at you from the water.", "none", ""],
  ["Gargoyle","true","interactable",0,0,"You see a scary looking gargoyle.", "none", ""],
  ["Blue Water Creature Left","true","nothing",0,0,"You see a water creature peer at you from the water.", "none", ""],
  ["Straw Block","true","nothing",0,0,"You see a light wooden wall.", "none", ""],
  ["Stone Wall","true","nothing",0,0,"You see a stone wall.", "none", ""],
  ["Ice Cream","false","garbage",0,0,"This ice cream is melting.. I wonder who would like this?", "none", ""],
  ["Biting Floor","false","damage",3,5,"It's a BITING floor, ouch!", "none", ""],
  ["Mushrooms","false","nothing",0,0,"It's a patch of mushrooms.", "none", ""],
  ["Buried Radish","false","interactable",0,0,"There's a radish buried here.", "none", ""],
  ["Unburied Radish","false","consumable",2,2,"It's a radish.","hp", "You eat the radish, it's healthy and nourishing."],
  ["Golden Key","false","useable",0,0,"It's a key made of gold, looks durable.", "none", ""],
  ["Drop Container","false","container",0,0,"You see a pouch on the ground (I wonder what's inside?).", "none", ""],
  ["Scorpion Pod","true","interactable",0,0,"It's a strange slimy pod.. is it quivering?", "none", ""],
  ["Scorpion Pod Open","true","interactable",0,0,"It's a strange slimy pod. What was in here?", "none", ""],
  ["Hermit Crab","false","garbage",0,0,"It's a Hermit Crab. I wonder where it's home is?", "none", ""],
  ["NPC 11 Girl with chains","true","npc",0,0,"NPC 11", "none", ""],
  ["Bow","false","weapon",1,3,"You see a longbow.", "none", ""],
  ["Sling","false","weapon",3,4,"It's a sling used to throw metal rocks.", "none", ""],
  ["Puddle","false","nothing",0,0,"You see a puddle of water on the ground.", "none", ""],
  ["Skeleton with Blue Necklace","false","interactable",0,0,"You see a corpse (something shiny catches your attention).", "none", ""],
  ["Unfinished Potion","false","garbage",0,0,"It's an unfinished potion.", "none", ""],
  ["Blue Necklace","false","garbage",0,0,"It's a beautiful, precious looking sapphire necklace.", "none", ""],
  ["Crossbow","false","weapon",2,4,"It's a crossbow.", "none", ""],
  ["Metal Ball Stack","false","garbage",0,0,"It's a stack of metal balls.", "none", ""],
  ["Red Staff","false","weapon",7,9,"It's a magical staff with a red gem on top!", "none", ""],
  ["Blue Staff","false","weapon",7,9,"It's a magical staff with a blue gem on top!", "none", ""],
  ["Red Necklace","false","garbage",0,0,"It's a golden necklace with a ruby gem.", "none", ""],
  ["OAB","false","garbage",0,0,"The Official Adventures Badge, ooh!", "none", ""],
  ["Dresser","true","nothing",0,0,"It's a wooden dresser.", "none", ""],
  ["Swamp Thing","true","nothing",0,0,"It's a swamp thing.. freaky.", "none", ""],
  ["Alchemist Table","true","interactable",0,0,"You see an alchemists potion full of odd potions.", "none", ""],
  ["NPC 12 Tweedle Dee","true","npc",0,0,"NPC 12", "none", ""],
  ["NPC 13 Tweedle Dum","true","npc",0,0,"NPC 13", "none", ""],
  ["Bar Table 1","true","nothing",0,0,"You see a bar table full of refuge.", "none", ""],
  ["Bar Table 2","true","nothing",0,0,"You see a bar table full of refuge.", "none", ""],
  ["Nezerath","true","nothing",0,0,"You see the dark mage Nezerath - RUN!!", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],    
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["Snail Mastah", "true", "nothing", 0, 0, "The snail mastah!", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["Alchemist Shelf", "true", "container", 0, 0, "You see a shelf full of strange potions.", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["Stairs Up", "true", "portal", 0, 0, "You see a large staircase.", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""],
    ["", "false", "nothing", 0, 0, "", "none", ""]
  ]
}
